apiVersion: apps/v1
kind: Deployment
metadata:
  name: instaplan-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instaplan-server
  template:
    metadata:
      labels:
        app: instaplan-server
    spec:
      containers:
      - name: instaplan-server
        image: instaplan-server:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: instaplan-server-service
spec:
  selector:
    app: instaplan-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP